
export const images = {
    KILLA: require(`../assets/images/killa.png`),
    KOT: require(`../assets/images/kot.png`),
    OSHPARENNI: require(`../assets/images/oshp.png`),
    RAMA: require(`../assets/images/rama.png`),
    SOBACHIHA: require(`../assets/images/sobachiha.png`),
    ERALASH: require(`../assets/images/eralash.png`),
    TRACTORMAN: require(`../assets/images/tractorman.png`),
    BOOMER: require(`../assets/images/boomer.jpg`),
};

export const sounds = {
    MAIN: require('../assets/sounds/main.mp3'),
    MERC: require('../assets/sounds/iz-merca.mp3'),
    ALE: require('../assets/sounds/ale.mp3'),
    BUHOI: require('../assets/sounds/buhoi.mp3'),
    SMOTRI: require('../assets/sounds/terpila_priehal.mp3'),
    PODARKOV: require('../assets/sounds/podarkov.mp3'),
    TERPILA: require('../assets/sounds/kto-terpila.mp3'),
    BESPREDEL: require('../assets/sounds/gde-pezpredel.mp3'),
    MICHISH: require('../assets/sounds/michish.mp3'),
    GORODISH: require('../assets/sounds/gorodish.mp3'),
    OBOSNUEM: require('../assets/sounds/obosnuem.mp3'),
    PROBLEM: require('../assets/sounds/komu-problem.mp3'),
    NEMI: require('../assets/sounds/ne-my-takie.mp3'),
    PODGON: require('../assets/sounds/podgon.mp3'),
    KANITEL: require('../assets/sounds/ne-zdorovay-kanitel.mp3'),
    ZAPRAVKA: require('../assets/sounds/jeto-nasha-zapravka.mp3'),
    MOLOKA: require('../assets/sounds/moloka-kupish.mp3'),
    POUBIVAUT: require('../assets/sounds/poubivajut-vas.mp3'),
    KATAFALKA: require('../assets/sounds/katafalka.mp3'),
    VLUDI: require('../assets/sounds/v-ludi.mp3'),
    NATEME: require('../assets/sounds/na-teme.mp3'),
    SUHAR: require('../assets/sounds/suhar.mp3'),
    ZAMERC: require('../assets/sounds/za-merc.mp3'),
    TR_PONYNA: require('../assets/sounds/ponyna.mp3'),
    TR_NAZR1: require('../assets/sounds/nazhraca.mp3'),
    TR_NAZR2: require('../assets/sounds/mogu_nazhraca.mp3'),
    V_STOILO: require('../assets/sounds/v-stoilo.mp3'),
    DO_VIESNENIA: require('../assets/sounds/zabrali-do-viesnenia.mp3'),
};
